### ISSUE TITLE
Tenant management and authentication

### ISSUE THREAD

**Issue by chunshao90** [apache/incubator-horaedb#929]
### Describe This Problem

Tenant management and authentication.

#### Simple solution
- [ ] config files, something like
```toml
[server.auth]
enable = true
# available values: file/ceresmeta
source = "file"

[server.auth.file]
username = "admin"
password = "secret-token"
```
#### Complex
- [ ] `ceresmeta` supports creating tenants and generating tokens.
- [ ] `ceresdb` supports identity verification.
